{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww18020\viewh15040\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 \
---\
- name: Set up elk\
  hosts: elk\
  become: True\
  tasks:\
   - sysctl:\
      name: vm.max_map_count\
      value: '262144'\
      sysctl_set: yes\
      state: present\
      reload: yes\
\
   - name: Increase virtual memory\
     command: sysctl -w vm.max_map_count=262144\
\
   - name: Increase virtual memory on restart\
     shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf\
\
   - name: docker.io\
     apt:\
       update_cache: yes\
       name: docker.io\
       state: present\
\
   - name: Install pip3\
     apt:\
        name: python3-pip\
        state: present\
\
   - name: Install Docker python\
     pip:\
       name: docker\
       state: present\
\
   - name: elk\
     docker_container:\
        name: sebp\
        image: sebp/elk:761\
        state: started\
        restart_policy: always\
        published_ports:\
          - "5601:5601"\
          - "9200:9200"\
          - "5044:5044"\
\
}