{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 ---\
- name: Install metric beat\
  hosts: webservers\
  become: true\
  tasks:\
  - name: Download metricbeat\
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb\
\
  - name: install metricbeat\
    command: dpkg -i metricbeat-7.6.1-amd64.deb\
\
  - name: drop in metricbeat config\
    copy:\
      src: /etc/ansible/metricbeat-config.yml\
      dest: /etc/metricbeat/metricbeat.yml\
\
  - name: enable and configure docker module for metric beat\
    command: metricbeat modules enable docker\
\
  - name: setup metric beat\
    command: metricbeat setup\
\
  - name: start metric beat\
    command: service metricbeat start\
}